import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Settings } from "@/components/Settings/Settings";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <div>
            <Link href="/">Go to home page</Link> <br />
            <Link href="/game">Go to game page</Link> <br />
            <Link href="/leaderboard">Go to leaderboard page</Link>
            <Settings />
          </div>
          <hr />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
